package com.akinpelumi.c2068220.mytu.ui.navigations


const val SPLASH_SCREEN = "SplashScreen"
const val MAIN_SCREEN = "MainScreen"
const val LOGIN_SCREEN = "LoginScreen"
const val SIGN_UP_SCREEN = "SignUpScreen"
const val FORGOT_PASSWORD_SCREEN = "ForgotPasswordScreen"
const val HOME_SCREEN = "HomeScreen"
const val ATTENDANCE_SCREEN = "AttendanceScreen"
const val TIMETABLE_SCREEN = "TimetableScreen"
const val BALANCE_SCREEN = "BalanceScreen"
const val LIBRARY_SCREEN = "LibraryScreen"
const val MODULE_SCREEN = "ModuleScreen"
const val TODO_SCREEN = "ToDoScreen"
const val VERIFY_EMAIL_SCREEN = "VerifyEmailScreen"
const val ALERT_SCREEN = "AlertScreen"
const val MAIL_SCREEN = "MailScreen"
const val PROFILE_SCREEN = "ProfileScreen"
const val CALENDAR_SCREEN = "CalendarScreen"